//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangWebTracNghiem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebTracNghiemOnline_FixEntities : DbContext
    {
        public WebTracNghiemOnline_FixEntities()
            : base("name=WebTracNghiemOnline_FixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Join_Quiz> Join_Quiz { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_of_Question> Type_of_Question { get; set; }
        public virtual DbSet<User_Admin> User_Admin { get; set; }
        public virtual DbSet<User_Answer> User_Answer { get; set; }
        public virtual DbSet<User_Ask> User_Ask { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
