//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangWebTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Answer
    {
        public int ID_User { get; set; }
        public string MSSV { get; set; }
    
        public virtual User User { get; set; }
    }
}
